name: sigrid-publish
on:
  push:
    branches:
      - "master"

jobs:
  sigridci:
    runs-on: ubuntu-latest
    steps:
      - name: https://github.com/hhs-semester-se-s2/2324-Projectgroep-1b
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Sigrid CI
        run: "git clone https://github.com/Software-Improvement-Group/sigridci.git sigridci"
      - name: "Run Sigrid CI"
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
        run: "./sigridci/sigridci/sigridci.py --customer hhsproject2 --system 2324-Projectgroep-1b --source . --publish"
